// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3z5kFrcradelywdgluwWvVTvIh4w1X0I',
    appId: '1:654981212155:web:7cc0b8ffabbe9e87544d5e',
    messagingSenderId: '654981212155',
    projectId: 'terobos3',
    authDomain: 'terobos3.firebaseapp.com',
    databaseURL: 'https://terobos3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'terobos3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZuYKmUYeSrxM2LItvr6x3Lhx8dXTqLCM',
    appId: '1:654981212155:android:5400527239e67076544d5e',
    messagingSenderId: '654981212155',
    projectId: 'terobos3',
    databaseURL: 'https://terobos3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'terobos3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZwOe0UXIklggVelJUejuF06e9MT8RsH8',
    appId: '1:654981212155:ios:7e2733ec0b5452ef544d5e',
    messagingSenderId: '654981212155',
    projectId: 'terobos3',
    databaseURL: 'https://terobos3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'terobos3.firebasestorage.app',
    iosBundleId: 'com.example.terobos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZwOe0UXIklggVelJUejuF06e9MT8RsH8',
    appId: '1:654981212155:ios:7e2733ec0b5452ef544d5e',
    messagingSenderId: '654981212155',
    projectId: 'terobos3',
    databaseURL: 'https://terobos3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'terobos3.firebasestorage.app',
    iosBundleId: 'com.example.terobos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3z5kFrcradelywdgluwWvVTvIh4w1X0I',
    appId: '1:654981212155:web:a9e0ccaf32a51613544d5e',
    messagingSenderId: '654981212155',
    projectId: 'terobos3',
    authDomain: 'terobos3.firebaseapp.com',
    databaseURL: 'https://terobos3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'terobos3.firebasestorage.app',
  );
}
