// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC7zG3VO2ccuBZCRyPN1U8iZlgNIiHnXI',
    appId: '1:189883996833:web:cf00122b429ad9acc26ee0',
    messagingSenderId: '189883996833',
    projectId: 'stasiunmini',
    authDomain: 'stasiunmini.firebaseapp.com',
    databaseURL: 'https://stasiunmini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stasiunmini.firebasestorage.app',
    measurementId: 'G-5B8EWYW3HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEloF_VgK94Qs2t76Wj3uNiI6L0zibQck',
    appId: '1:189883996833:android:482ef200ee9d19f9c26ee0',
    messagingSenderId: '189883996833',
    projectId: 'stasiunmini',
    databaseURL: 'https://stasiunmini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stasiunmini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkffL5SMvBk_r3Dka6D9Hy004OpNy32pg',
    appId: '1:189883996833:ios:7cd8433b70f5a6a9c26ee0',
    messagingSenderId: '189883996833',
    projectId: 'stasiunmini',
    databaseURL: 'https://stasiunmini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stasiunmini.firebasestorage.app',
    iosBundleId: 'com.example.terobos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkffL5SMvBk_r3Dka6D9Hy004OpNy32pg',
    appId: '1:189883996833:ios:7cd8433b70f5a6a9c26ee0',
    messagingSenderId: '189883996833',
    projectId: 'stasiunmini',
    databaseURL: 'https://stasiunmini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stasiunmini.firebasestorage.app',
    iosBundleId: 'com.example.terobos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3z5kFrcradelywdgluwWvVTvIh4w1X0I',
    appId: '1:654981212155:web:a9e0ccaf32a51613544d5e',
    messagingSenderId: '654981212155',
    projectId: 'terobos3',
    authDomain: 'terobos3.firebaseapp.com',
    databaseURL: 'https://terobos3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'terobos3.firebasestorage.app',
  );

}